name: 2022-ADS_plaque
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.8
  - bioconda::fastqc=0.11.9
  - bioconda::cutadapt=3.3
  - bioconda::seqtk=1.3
  - bioconda::star=2.7.5c
  - bioconda::kraken2=2.1.2
  - bioconda::samtools=1.12
  - bioconda::subread=2.0.1
  - bioconda::goatools=1.2.3
  - bioconda::bowtie2=2.4.5

