name: 2022-ADS_plaque-analysis
channels:
  - defaults
  - bioconda
  - conda-forge
  - anaconda
dependencies:
  - conda-forge::r-base=4.1.2
  - bioconda::bioconductor-deseq2=1.34.0
  - bioconda::bioconductor-limma=3.50.1
  - bioconda::bioconductor-edger=3.36.0
  - bioconda::bioconductor-glimma=2.4.0
  - anaconda::jupyter=1.0.0
  - conda-forge::r-irkernel=1.3
  - conda-forge::r-stringi=1.7.6
  - bioconda::cutadapt=4.0
  - bioconda::entrez-direct=16.2