#PBS -N STAR-map-46PD_S14
#PBS -l select=1:ncpus=40:mem=750gb
#PBS -l walltime=138:00:00
#PBS -j oe
#PBS -m abe
#PBS -q bigmem

# load module
module add star/2.7.5c

# move into scratch
cd /scratch1/amann3/uf_rnaseq/

# run command
STAR --runThreadN 40 \
	--genomeDir kraken_refgenomes/GenomeDir \
	--readFilesIn <(gunzip -c 46PD_S14_R1_001.fastq.gz) <(gunzip -c 46PD_S14_R2_001.fastq.gz) \
	--outFileNamePrefix 46PD_S14 \ 
	--outSAMtype BAM Unsorted \ 
	--outReadsUnmapped 46PD_S14.unmapped.bam \ 
	--quantMode TranscriptomeSAM GeneCounts \ 
	--alignIntronMax 1 \
	--chimOutType SeparateSAMold
