#PBS -N STAR-map-73PF_S24
#PBS -l select=1:ncpus=40:mem=750gb
#PBS -l walltime=336:00:00
#PBS -j oe
#PBS -m abe
#PBS -q cugi

# load module
source activate star2.7.5c

# move into scratch
cd /scratch1/amann3/uf_rnaseq/

# run command
STAR --runThreadN 40 \
	--genomeDir kraken_refgenomes/GenomeDir \
	--readFilesIn <(gunzip -c 73PF_S24_R1_001.fastq.gz) <(gunzip -c 73PF_S24_R2_001.fastq.gz) \
	--outFileNamePrefix 73PF_S24 \ 
	--outSAMtype BAM Unsorted \ 
	--outReadsUnmapped 73PF_S24.unmapped.bam \ 
	--quantMode TranscriptomeSAM GeneCounts \ 
	--alignIntronMax 1 \
	--chimOutType SeparateSAMold

