name: uf_rnaseq
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.8
  - bioconda::trinity=2.8.5
  - bioconda::fastqc=0.11.9
  - bioconda::cutadapt=3.3
  - bioconda::seqtk=1.3
  - conda-forge::parallel=20210222
  - bioconda::samtools=1.12
  - bioconda::subread=2.0.1
  - bioconda::bowtie2=2.4.2
  - bioconda::vsearch=2.17.0
