#PBS -N 20PD_S6
#PBS -l select=1:ncpus=40:mem=750gb
#PBS -l walltime=72:00:00
#PBS -j oe
#PBS -m abe
#PBS -q bigmem

# load module
module add star/2.7.5c

# move into scratch
cd /scratch1/amann3/uf_rnaseq/homd_mapped/

# run command
STAR --runThreadN 40 \
	--genomeDir GenomeDir \
	--readFilesIn <(gunzip -c ../20PD_S6_R1_001.fastq.gz) <(gunzip -c ../20PD_S6_R2_001.fastq.gz) \
	--outFileNamePrefix 20PD_S6 \ 
	--outSAMtype BAM Unsorted \ 
	--outReadsUnmapped 20PD_S6.unmapped.bam \ 
	--quantMode TranscriptomeSAM GeneCounts \ 
	--alignIntronMax 1 \
	--chimOutType SeparateSAMold
