#PBS -N STAR-genomeGenerate
#PBS -l select=1:ncpus=10:mem=750gb
#PBS -l walltime=72:00:00
#PBS -j oe
#PBS -m abe
#PBS -q bigmem

# load module
module add star/2.7.5c

# move into scratch
cd /scratch1/amann3/uf_rnaseq/homd_mapped

# run command
STAR --runMode genomeGenerate --genomeFastaFiles ALL_genomes.fna  --runThreadN 10 --limitGenomeGenerateRAM 228697571594 --sjdbGTFfile ALL_genomes.gtf --genomeChrBinNbits 10 --limitSjdbInsertNsj 3204994
