#PBS -N STAR-map
#PBS -l select=1:ncpus=40:mem=500gb
#PBS -l walltime=138:00:00
#PBS -j oe
#PBS -m abe
#PBS -q bigmem

# load module
module add star/2.7.5c

# move into scratch
cd /scratch1/amann3/uf_rnaseq/

# run command
ls *R1*fastq.gz | sed 's/_R1_001.fastq.gz//' | while read line; do STAR \
	--runThreadN 20 \
	--genomeDir kraken_refgenomes/GenomeDir \
	--readFilesIn <(gunzip -c $line\_R1_001.fastq.gz) <(gunzip -c $line\_R2_001.fastq.gz) \
	--outFileNamePrefix $line \
	--outSAMtype BAM Unsorted \
	--outReadsUnmapped $line.unmapped.bam \
	--quantMode TranscriptomeSAM GeneCounts \
	--alignIntronMax 1 \
	--chimOutType SeparateSAMold ; done
